version: "3"
services:
  app:
    container_name: user_api
    restart: always
    build: .
    ports:
      - "8080:8000"
    links:
      - mongo
      - redis:redis
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27018"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  